apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-backend-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  DATABASE_URL: postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}