apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-frontend
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
  selector:
    app: {{ include "chart.fullname" . }}-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-backend
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 5000
  selector:
    app: {{ include "chart.fullname" . }}-backend