name: Helm Chart CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-package:
    name: Lint and Package Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Lint Helm Chart
        run: |
          helm lint .

      - name: Package Helm Chart
        run: |
          helm package .
          ls -l *.tgz

  validate-in-cluster:
    name: Validate Helm Chart in Kubernetes
    runs-on: ubuntu-latest
    needs: lint-and-package

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Set up KinD Cluster
        uses: helm/kind-action@v1.4.0
        with:
          version: v0.20.0

      - name: Install Helm Chart in KinD Cluster
        run: |
          helm install test-release . --namespace test --create-namespace
          kubectl get all -n test  # Verify that resources are created

      - name: Uninstall Helm Chart
        run: |
          helm uninstall test-release --namespace test